### ISSUE TITLE
Change title of blog

### ISSUE THREAD

**Issue by hubertle43100** [hubertle43100/minimal-blog#23]
Change to title to something like
`UXUI Frontend designs blog` or
`Blogs for developer/designers`

instead of just _ALL POST_

<img width="799" alt="Screenshot 2024-02-08 at 12 12 49 PM" src="https://github.com/hubertle43100/minimal-blog/assets/56861838/60ead677-6250-4cb0-9387-12dca8889a42">

**Comment by Shoyebaktar-shirol** [comment]
hey @hubertle43100 , Please assign me this issue i am eager to contribute on (minimal - Blog)

**Comment by lourdrivera123** [comment]
@hubertle43100 Created a PR for this, kindly review

**Comment by hubertle43100** [comment]
**@Shoyebaktar-shirol** 

Sorry, I couldn't get to you for the assignment feel free to `just tackle the issue without being assigned.`
